"""Add share tokens

Null until an owner explicitly shares an analysis. Unique and indexed
because the token is the sole lookup key for the public routes.

Revision ID: 01c32ebdc9cc
Revises: 2f21e356e0b2
Create Date: 2026-07-24 16:01:04.819036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01c32ebdc9cc'
down_revision = '2f21e356e0b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_token', sa.String(length=43), nullable=True))
        batch_op.add_column(sa.Column('shared_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_analyses_share_token'), ['share_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_share_token'))
        batch_op.drop_column('shared_at')
        batch_op.drop_column('share_token')

    # ### end Alembic commands ###
